### ISSUE TITLE
大佬好，在运行代码的时候有几个问题

### ISSUE THREAD

**Issue by laoba111** [Rooooyy/HILL#1]
raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.RunDir'> for field run is not allowed: use default_factory
这个报错是在python data_wos.py的时候产生的，本人实在不懂，请教一下大佬，感谢

**Comment by Rooooyy** [comment]
你好，这个问题我没有遇到过，推测是fairseq的问题，版本一定要用0.10.2
如果换了版本还不行还可以试试几个办法：
1. 57行注释掉，58行取消注释；64-67行注释掉，68-71行取消注释
2. 改用HPT的预处理代码方式[https://github.com/wzh9969/HPT](https://github.com/wzh9969/HPT)，不需要fairseq，但是相应的数据读取代码也要你自己仿照修改

**Comment by laoba111** [comment]
感谢大佬指导🌹



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: roy_zh ***@***.***&gt;
发送时间: 2024年4月17日 14:57
收件人: Rooooyy/HILL ***@***.***&gt;
抄送: laoba111 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Rooooyy/HILL] 大佬好，在运行代码的时候有几个问题 (Issue #1)





 
你好，这个问题我没有遇到过，推测是fairseq的问题，版本一定要用0.10.2
 如果换了版本还不行还可以试试几个办法：
  
57行注释掉，58行取消注释；64-67行注释掉，68-71取消注释
 
改用的预处理代码方式https://github.com/wzh9969/HPT，不需要fairseq，但是相应的数据读取代码也要你自己仿照修改
