### ISSUE TITLE
晚上好，关于代码中的小疑问

### ISSUE THREAD

**Issue by xuuwb** [Rooooyy/HILL#3]
晚上好！我观看了您的代码，我发现在contrast.py中的第344行代码self.attn = FusionLayer1(config, local_config)可能存在问题，代码中并没有定义FusionLayer1，并且没有调用self.attn，请问这一行代码是多余的吗

![1730468086527](https://github.com/user-attachments/assets/3a6f9a45-d664-4e15-a981-89152f479ba4)

**Comment by Rooooyy** [comment]
搞消融实验的代码混进了release里面，把self.attn相关usage注释掉就好，可以认为是多余的
